platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.2'
pod 'MJExtension', '~> 2.5.3'
pod 'DZNEmptyDataSet'
pod 'ChameleonFramework'
pod 'MJRefresh'
pod 'MLInputDodger'
pod 'MBProgressHUD'